In [40]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

In [41]:
file = open("malayalam.txt", "r", encoding = "utf8")
lines = []
for i in file:
    lines.append(i)
data = ""
for i in lines:
  data = ' '. join(lines) 
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')
data = data.split()
data = ' '.join(data)
data[:500]

'അഹിംസാ പരമോ ധർമ്മഃ എന്ന തത്വത്തിന്റെ അടിത്തറയുണ്ടാക്കി, വിവിധ പ്രസ്ഥാനങ്ങളിലൂടെ, മഹാത്മാഗാന്ധി രാജ്യത്തെ അടിമത്തത്തിന്റെ ചങ്ങലകളിൽ നിന്ന് മോചിപ്പിച്ചു. അദ്ദേഹം ഒരു നല്ല രാഷ്ട്രീയക്കാരനും അതുപോലെ നല്ല വാഗ്മിയും ആയിരുന്നു. അദ്ദേഹം പറഞ്ഞ വാക്കുകൾ ഇന്നും ജനങ്ങൾ ആവർത്തിക്കുന്നു. 1869 ഒക്ടോബർ 2ന് ഗുജറാത്തിലെ പോർബന്തറിലാണ് മഹാത്മാഗാന്ധി ജനിച്ചത്. പിതാവിന്റെ പേര് കരംചന്ദ് ഗാന്ധി, അമ്മയുടെ പേര് പുത്ലിബായി. മഹാത്മാഗാന്ധിയുടെ പിതാവ് ചെറിയ നാട്ടുരാജ്യമായ കത്തിയവാറിലെ (പോർബന്തർ) ദിവാനായിരുന്നു. ആ പ്രദേശത്തെ '

In [42]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

pickle.dump(tokenizer, open('token.pkl', 'wb'))

sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[18, 19, 20, 21, 22, 23, 24, 25, 3, 26, 27, 28, 4, 29, 2]

In [43]:
len(sequence_data)

170

In [44]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

141


In [45]:
sequences = []

for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)
    
print("The Length of sequences are: ", len(sequences))
sequences = np.array(sequences)
sequences[:10]

The Length of sequences are:  167


array([[18, 19, 20, 21],
       [19, 20, 21, 22],
       [20, 21, 22, 23],
       [21, 22, 23, 24],
       [22, 23, 24, 25],
       [23, 24, 25,  3],
       [24, 25,  3, 26],
       [25,  3, 26, 27],
       [ 3, 26, 27, 28],
       [26, 27, 28,  4]])

In [46]:
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])
    
X = np.array(X)
y = np.array(y)

In [47]:
print("Data: ", X[:10])
print("Response: ", y[:10])

Data:  [[18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25  3]
 [25  3 26]
 [ 3 26 27]
 [26 27 28]]
Response:  [21 22 23 24 25  3 26 27 28  4]


In [48]:
y = to_categorical(y, num_classes=vocab_size)
y[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [49]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

In [50]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 3, 10)             1410      
_________________________________________________________________
lstm_4 (LSTM)                (None, 3, 1000)           4044000   
_________________________________________________________________
lstm_5 (LSTM)                (None, 1000)              8004000   
_________________________________________________________________
dense_4 (Dense)              (None, 1000)              1001000   
_________________________________________________________________
dense_5 (Dense)              (None, 141)               141141    
Total params: 13,191,551
Trainable params: 13,191,551
Non-trainable params: 0
_________________________________________________________________


In [51]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint("model.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001))
model.fit(X, y, epochs=100, batch_size=64, callbacks=[checkpoint])

Epoch 1/100
3/3 [==============================] - 3s 11ms/step - loss: 4.9495

Epoch 00001: loss improved from inf to 4.94975, saving model to model.h5
Epoch 2/100
3/3 [==============================] - 0s 10ms/step - loss: 4.9455

Epoch 00002: loss improved from 4.94975 to 4.94561, saving model to model.h5
Epoch 3/100
3/3 [==============================] - 0s 10ms/step - loss: 4.9393

Epoch 00003: loss improved from 4.94561 to 4.93715, saving model to model.h5
Epoch 4/100
3/3 [==============================] - 0s 10ms/step - loss: 4.9205

Epoch 00004: loss improved from 4.93715 to 4.92035, saving model to model.h5
Epoch 5/100
3/3 [==============================] - 0s 10ms/step - loss: 4.8731

Epoch 00005: loss improved from 4.92035 to 4.86381, saving model to model.h5
Epoch 6/100
3/3 [==============================] - 0s 10ms/step - loss: 4.8473

Epoch 00006: loss did not improve from 4.86381
Epoch 7/100
3/3 [==============================] - 0s 10ms/step - loss: 4.8258

Epoch 00007:


Epoch 00054: loss improved from 0.50380 to 0.42769, saving model to model.h5
Epoch 55/100
3/3 [==============================] - 0s 13ms/step - loss: 0.3574

Epoch 00055: loss improved from 0.42769 to 0.38556, saving model to model.h5
Epoch 56/100
3/3 [==============================] - 0s 12ms/step - loss: 0.3222

Epoch 00056: loss improved from 0.38556 to 0.33210, saving model to model.h5
Epoch 57/100
3/3 [==============================] - 0s 12ms/step - loss: 0.2843

Epoch 00057: loss improved from 0.33210 to 0.27209, saving model to model.h5
Epoch 58/100
3/3 [==============================] - 0s 12ms/step - loss: 0.2106

Epoch 00058: loss improved from 0.27209 to 0.21722, saving model to model.h5
Epoch 59/100
3/3 [==============================] - 0s 12ms/step - loss: 0.2061

Epoch 00059: loss improved from 0.21722 to 0.21399, saving model to model.h5
Epoch 60/100
3/3 [==============================] - 0s 12ms/step - loss: 0.1612

Epoch 00060: loss improved from 0.21399 to 0.16886,

In [57]:
from tensorflow.keras.models import load_model
import numpy as np
import pickle

model = load_model('model.h5')
tokenizer = pickle.load(open('token.pkl', 'rb'))

def Predict_Next_Words(model, tokenizer, text):
  sequence = tokenizer.texts_to_sequences([text])
  sequence = np.array(sequence)
  preds = np.argmax(model.predict(sequence))
  predicted_word = ""
  for key, value in tokenizer.word_index.items():
      if value == preds:
          predicted_word = key
          break
  print(predicted_word)
  return predicted_word

In [59]:
while(True):
  text = input("Enter your line: ")
  if text == "0":
      print("Execution completed.....")
      break
  else:
      try:
          text = text.split(" ")
          text = text[-3:]
          print(text)
          Predict_Next_Words(model, tokenizer, text)
      except Exception as e:
        print("Error occurred: ",e)
        continue

Enter your line: അഹിംസാ പരമോ ധർമ്മഃ 
['പരമോ', 'ധർമ്മഃ', '']
എന്ന
Enter your line: 0
Execution completed.....
